spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beautysaloon?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: beautysaloon
    password: beautySALOON2020***
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop